[apis]
rke2-lb ansible_host=192.168.1.14

[masters]
server-01 ansible_host=192.168.1.16
server-02 ansible_host=192.168.1.20
server-03 ansible_host=192.168.1.18

[workers]
node-01 ansible_host=192.168.1.21
node-02 ansible_host=192.168.1.22
node-03 ansible_host=192.168.1.23

[k8s_cluster:children]
masters
workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/root/.ssh/id_ed25519
ansible_user=root
